feat: спринт 14. попытка 1.
misandr/java-shareit pull request #2
Opened 2023-03-05 14:41 UTC by misandr

2023-03-06 15:00 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохо - давай поправим детали и будет зачет =)

2023-03-06 15:00 UTC, krylov-sergey-sergeevich commented on pom.xml
> +            <artifactId>annotations</artifactId>
Не очень рекомендую, но не критично

2023-03-06 15:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
Для чего это нам тут?

2023-03-06 15:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
Аналогичный вопрос, зачем это тут

2023-03-06 15:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Enumerated(EnumType.STRING)
@Column(name = "status", nullable = false)

2023-03-06 15:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        LocalDateTime timeNow = LocalDateTime.now();
Давай создадим класс DateUtils и будем создавать объекты времени через него, это позволит унифицировать способ получения времени и если будут правки делать их в 1 месте.

2023-03-06 15:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        LocalDateTime timeNow = LocalDateTime.now();
DateUtils.now() - будет

2023-03-06 15:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +@Qualifier("ItemServiceImpl")
Для чего это? ("ItemServiceImpl")

2023-03-06 18:45 UTC, misandr commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
Без этой строчки ответ выглядел так: 
{
    "id": 1,
    "name": "update",
    "email": "update@user.com",
    "hibernateLazyInitializer"
}{
    "error": "An unexpected error has occurred."
}

2023-03-07 06:07 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-03-12 18:22 UTC, merged