feat: спринт 15. попытка 1.
misandr/java-shareit pull request #3
Opened 2023-03-18 15:13 UTC by misandr

2023-03-20 19:49 UTC, krylov-sergey-sergeevich requested changes
Привет :) В целом неплохой pr, но кое что улучшим

Бизнес код неплох, там по мелочам отписал

- Можешь почитать про verify в Mockito полезная штука
- Исключения просьба делать более подробными, местами отметил, но думаю есть еще случаи где можно лучше

Буду ждать с доработкой =)

2023-03-20 19:49 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                throw new ValidationException("Item not available!");
Какой айтем?

2023-03-20 19:49 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                        throw new ValidationException("Status booking bad!");
какого букинга

2023-03-20 19:49 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new ValidationException("Bad range for items!");
побольше подробностей

2023-03-20 19:49 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTest.java
> +//package ru.practicum.shareit.booking;
Почему так?)

2023-03-21 17:54 UTC, misandr commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTest.java
> +//package ru.practicum.shareit.booking;
Пытался достичь нужного значения для покрытия тестами)

2023-03-22 20:35 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки  - зачет!

2023-03-22 20:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/Range.java
> +    Integer from;
Модификаторы доступа

2023-03-22 20:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/Range.java
> +public class Range {
рекомендую в таких утилитных классах делать конструктор скрытым приватным и делать методы static of() вместо конструктора , это своеобразный стиль кода

2023-03-29 17:50 UTC, merged