feat: спринт 16. попытка 1.
misandr/java-shareit pull request #4
Opened 2023-04-02 10:34 UTC by misandr

2023-04-03 04:45 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо сделано, отметил некоторые места о которых рекомендую подумать и буду ждать с правками для зачета =)

2023-04-03 04:45 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<Object> addItem(@RequestHeader("X-Sharer-User-Id") long userId,
@RequestHeader(HEADER_USER_ID)

2023-04-03 04:45 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> addUser(@RequestBody @Valid User user) {
`ResponseEntity<Object>` - мы не знаем какой объект вернем?

2023-04-03 04:45 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +
пустая строка лишняя

2023-04-03 04:45 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> updateUser(@PathVariable Long userId, @Valid @RequestBody User user) {
`ResponseEntity<Object>` - мы не знаем какой объект вернем?

2023-04-03 04:45 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> getUser(@PathVariable Long userId) {
`ResponseEntity<Object>` - мы не знаем какой объект вернем?

2023-04-03 04:45 UTC, krylov-sergey-sergeevich commented on server/src/main/java/ru/practicum/shareit/Range.java
> +    private Integer from;
можно вроде как: private final

2023-04-03 04:45 UTC, krylov-sergey-sergeevich commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                throw new ValidationException("Unknown state: UNSUPPORTED_STATUS");
тут throw new ValidationException("Unknown state: UNSUPPORTED_STATUS");
а выше было throw ExceptionFactory.createValidationException(log, "Unknown state: UNSUPPORTED_STATUS");

давай единому стилю придерживаться =)

2023-04-03 04:45 UTC, krylov-sergey-sergeevich commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (booking.isPresent()) {
заметил что часто повторяется
Optional<Booking> booking = bookingRepository.findById(bookingId);
        if (booking.isPresent()) {
....

нельзя ли вынести в метод удобный? чтобы не думать и сразу получать объект с предвыполнеными проверками что он существует

2023-04-03 04:45 UTC, krylov-sergey-sergeevich commented on server/src/main/java/ru/practicum/shareit/exceptions/ExceptionFactory.java
Мне класс не нравится - но это не обязательно фиксить, по желанию

Поясню: 
1) мы сюда передаем логгер что ну такое, нет прям причин сказать что это плохо, и я сходу не скажу чем это плохо, но это неправильно как будто бы тк логгер это инфраструктурная штука она большая фундаментальная и мы ее передавать по методам не должны
2) по сути в коде теперь есть 2 подхода где с помощью фабрики создается а где просто по старинке new () и это вводит путаницу, типо почему тут так а тут так?
3) Чем механизм проще тем лучше, поэтому идею с фабрикой это ок, но сделай ее проще а именно просто сделай 4-10-100 простых названий для классов исключений которые внутри себя будут собирать корректные сообщения, а логгирование оставь другим "дядям" например RestControllerAdvice или просто сам руками в методах где кидаешь исключение пишешь лог

2023-04-03 21:05 UTC, misandr commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> addUser(@RequestBody @Valid User user) {
Я не совсем понял, как правильно это сделать. В одном месте я подправил, но не уверен, что именно это имелось ввиду. Если такой вариант устроит, то я его реализую везде. Ну или мне будет нужна подсказка)

2023-04-04 07:06 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки, на счет User это да правильно но код стал как то гораздо сложнее, наверно можно это убрать и не усложнять логику - тут я был неправ.

Ставлю зачет тк критичных моментов нет, удачи =)

2023-04-04 07:06 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<User> addUser(@RequestBody @Valid User user) {
да, так лучше

2023-04-04 17:11 UTC, merged